version: '3.8'

services:
  aws-visualizer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=website.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro